---
title: "Programming assignment 1"
author: "ljuba80"
output:
  html_document:
    fig_width: 11
    keep_md: yes
    theme: readable
    toc: yes
---


## Loading and preprocessing the data

```{r,echo=TRUE}
library("ggplot2")
data<-read.csv("activity.csv");
data1<-subset(data,!is.na(data$step))
data1$date<-as.character(data1$date)
```

## What is mean total number of steps taken per day?
```{r,echo=TRUE}
tot<-with(data1, tapply(steps, date, sum))
hist(tot,breaks=50,main="Total number of steps")
mean(tot)
median(tot)
```



## What is the average daily activity pattern?

```{r,echo=TRUE}
avgNSteps<-with(data1, tapply(steps, interval, mean))
plot(unique(data1$interval),avgNSteps,main="Avg daily activity",
     ylab="av # of steps",xlab="interval",col='red',lwd=0,type='n')
lines(unique(data1$interval),avgNSteps,col='red');

#gives 206.1698 in 835
avgNSteps[avgNSteps==max(avgNSteps)]
```


## Imputing missing values

```{r,echo=TRUE}
numOfMissingVal <- sum(is.na(data$steps) | is.na(data$interval))
numOfMissingVal
```


## Are there differences in activity patterns between weekdays and weekends?

```{r,echo=TRUE}
avgPerInt<-data.frame(steps=avgNSteps,intervals=unique(data$interval))
data$steps[is.na(data$steps)]=avgPerInt$steps
tot1<-with(data, tapply(steps, date, sum))
hist(tot1,breaks=50,main="Total number of steps - imputed missing values")
mean(tot1)
median(tot1)
#adding new variable to data frame
#data<-cbind(data,data.frame(typeOfDay=weekdays(as.Date(data$date))))

data<-cbind(data,data.frame(typeOfDay=""))
levels(data$typeOfDay)<-c("weekday","Weekend")
data$typeOfDay[weekdays(as.Date(data$date))!=as.character("Saturday") & weekdays(as.Date(data$date))!=as.character("Sunday")]=levels(data$typeOfDay)[1]
data$typeOfDay[weekdays(as.Date(data$date))==as.character("Saturday") | weekdays(as.Date(data$date))==as.character("Sunday")]=levels(data$typeOfDay)[2]
#weekday
ndf1<-subset(data,typeOfDay==levels(data$typeOfDay)[1])
avgNSteps1<-with(ndf1, tapply(steps, interval, mean))
#weekend
ndf2<-subset(data,typeOfDay==levels(data$typeOfDay)[2])
avgNSteps2<-with(ndf2, tapply(steps, interval, mean))
avgNumSteps=c(avgNSteps1,avgNSteps2)
wDays=c(rep(levels(data$typeOfDay)[1],length(avgNSteps1)),
        rep(levels(data$typeOfDay)[2],length(avgNSteps2)))
Interval=c(unique(ndf1$interval),unique(ndf2$interval))
df = data.frame(avgNumSteps,wDays,Interval)
g<-ggplot(df,aes(Interval,avgNumSteps))
p<-g+geom_line()  + facet_grid(.~wDays)
print(p)
```

